# standard
python test_classifier.py --seed 1 --model_save_path ./Saved_Models/Pretrained_Models/id_CIFAR100_model_WideResNet-40-2-0.3_seed_1.pt  --model_type WideResNet-40-2-0.3 --num_epochs_finetune 10 --val_batch_size 4 --finetune_pretrained_model --no_train --lr 0.001 --run_name standard --finetune_params all --ood_dataset_name SVHN --ood_dataset_path ./data --id_dataset_name CIFAR100 --num_classes 100 --id_dataset_end_label 100 --ood_dataset_start_label 0 --ood_dataset_end_label 10 --ood_unlabeled_end_index 100 --ood_test_start_index 100 --ood_test_end_index 200 --id_unlabeled_end_index 50 --id_test_start_index 50 --id_test_end_index 100 --id_train_end_index 400 --id_val_start_index 400 --train_batch_size 32 --repeat_unlabeled_set 3 --confidence_weight 0.5

# outlier exposure
python test_classifier.py --seed 1 --model_save_path ./Saved_Models/Pretrained_Models/cifar100_wrn_oe_tune_epoch_9.pt --no_train --model_type WideResNet-40-2-0.3 --num_epochs_finetune 10 --val_batch_size 16 --finetune_pretrained_model --lr 0.001 --run_name outlier_exposure --finetune_params all --ood_dataset_name CIFAR10 --ood_dataset_path ./data --id_dataset_name CIFAR100 --num_classes 100 --id_dataset_end_label 100 --ood_dataset_start_label 0 --ood_dataset_end_label 10 --ood_unlabeled_end_index 100 --ood_test_start_index 100 --ood_test_end_index 200 --id_unlabeled_end_index 50 --id_test_start_index 50 --id_test_end_index 100 --id_train_end_index 400 --id_val_start_index 400 --train_batch_size 32 --repeat_unlabeled_set 3

# energy based finetuning
python test_classifier.py --seed 1 --model_save_path ./Saved_Models/Pretrained_Models/cifar100_wrn_s1_energy_ft_epoch_9.pt --no_train --model_type WideResNet-40-2-0.3 --num_epochs_finetune 10 --val_batch_size 16 --finetune_pretrained_model --lr 0.001 --run_name energy_finetuning --finetune_params all --ood_dataset_name CIFAR10 --ood_dataset_path ./data --id_dataset_name CIFAR100 --num_classes 100 --id_dataset_end_label 100 --ood_dataset_start_label 0 --ood_dataset_end_label 10 --ood_unlabeled_end_index 100 --ood_test_start_index 100 --ood_test_end_index 200 --id_unlabeled_end_index 50 --id_test_start_index 50 --id_test_end_index 100 --id_train_end_index 400 --id_val_start_index 400 --train_batch_size 32 --repeat_unlabeled_set 3

# our method
python test_classifier.py --seed 1 --model_save_path ./Saved_Models/Pretrained_Models/id_CIFAR100_model_ResNet18_seed_1.pt  --model_type ResNet18 --num_epochs_finetune 10 --val_batch_size 4 --finetune_pretrained_model --lr 0.001 --run_name ours --finetune_params all --ood_dataset_name SVHN --ood_dataset_path ./data --id_dataset_name CIFAR100 --num_classes 100 --id_dataset_end_label 100 --ood_dataset_start_label 0 --ood_dataset_end_label 10 --ood_unlabeled_end_index 100 --ood_test_start_index 100 --ood_test_end_index 200 --id_unlabeled_end_index 50 --id_test_start_index 50 --id_test_end_index 100 --id_train_end_index 400 --id_val_start_index 400 --train_batch_size 32 --repeat_unlabeled_set 3 --confidence_weight 0.5
