configs = {
    "cifar10": {
        "task_name": "cifar10_cifar10c",
        "id_dataset": "cifar10",
        "ood_dataset": "cifar10c",
        "num_classes": 10,
        "reward": 2.2,
        "finetuning_set_batch_size": 64,
        "uncertainty_set_batch_size": 128,
        "test_batch_size": 200,
        "momentum": 0.9,
        "es": -1,
        "decay": 0.0005,
        "num_workers": 4,
        "num_epochs": 10,
    },
    "waterbirds": {
        "task_name": "waterbirds",
        "id_dataset": "waterbirds-train",
        "ood_dataset": "waterbirds-test",
        "num_classes": 2,
        "reward": 2.2,
        "finetuning_set_batch_size": 64,
        "uncertainty_set_batch_size": 128,
        "test_batch_size": 200,
        "confidence_weight": 0.5,
        "lr": 0.001,
        "momentum": 0.9,
        "es": -1,
        "decay": 0.0005,
        "num_workers": 4,
        "num_epochs": 20,
    },
    "camelyon17": {
        "task_name": "camelyon17",
        "id_dataset": "camelyon17-train",
        "ood_dataset": "camelyon17-test",
        "num_classes": 2,
        "reward": 1.6,
        "finetuning_set_batch_size": 32,
        "uncertainty_set_batch_size": 32,
        "test_batch_size": 32,
        "confidence_weight": 0.5,
        "momentum": 0.9,
        "es": -1,
        "decay": 0.0005,
        "num_workers": 4,
        "num_epochs": 1,
        "optimizer": "AdamW",
        "optimizer_args": {
            "weight_decay": 0.01,
            "amsgrad": True,
            "betas": (0.9, 0.999),
        },
        "target_resolution": (96, 96),
    },
    "fmow": {
        "task_name": "fmow",
        "id_dataset": "fmow-train",
        "ood_dataset": "fmow-test",
        "num_classes": 62,
        "reward": 1.6,
        "finetuning_set_batch_size": 16,
        "uncertainty_set_batch_size": 32,
        "test_batch_size": 64,
        "confidence_weight": 0.5,
        "momentum": 0.9,
        "es": -1,
        "decay": 0.0005,
        "num_workers": 4,
        "num_epochs": 10,
        "optimizer": "AdamW",
        "optimizer_args": {
            "weight_decay": 0.01,
            "amsgrad": True,
            "betas": (0.9, 0.999),
        },
    },
}
